repos:
  - repo: local
    hooks:
      - id: yapf
        name: yapf
        entry: poetry run yapf
        language: system
        pass_filenames: false
        args: [ "-i", "-r", "src/", "tests/" ]
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        pass_filenames: false
        args: [ "src/", "tests/" ]
      - id: pytest
        name: pytest with coverage
        entry: poetry run python -m dotenv run -- pytest
        language: system
        pass_filenames: false
        args: [ "--cov=src", "--cov-report=xml" ]