openapi: 3.1.0
info:
  contact:
    name: BoredLabsHQ
    url: https://github.com/BoredLabsHQ/Concord
  description: "API for Concord, an AI-powered semantic extraction and recommendation\
    \ platform for networked communities."
  title: Concord API
  version: 1.0.0
servers:
- url: http://localhost:8000/
paths:
  /servers/register:
    post:
      description: "Registers a new server/group with configurable metadata, including\
        \ platform and authentication token."
      operationId: registerServer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServerRegisterRequest'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerRegisterResponse'
          description: Server/group registered successfully.
        "400":
          description: Invalid input data or missing required fields.
        "409":
          description: Conflict if a server/group with the same name exists.
      summary: Register a new server/group
      tags:
      - servers
  /channels/{platform_id}/{channel_id}/messages:
    post:
      description: Processes a message feed from a specified channel and updates associated
        topics.
      operationId: postChannelMessages
      parameters:
      - explode: false
        in: path
        name: platform_id
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: channel_id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChannelMessagesRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannelMessagesResponse'
          description: Messages processed successfully.
        "400":
          description: Invalid input data.
      summary: Upload channel messages for processing
      tags:
      - channels
  /channels/{platform_id}/{channel_id}/related:
    get:
      description: Fetches channels discussing topics similar to the specified channel.
      operationId: getRelatedChannels
      parameters:
      - explode: false
        in: path
        name: platform_id
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: channel_id
        required: true
        schema:
          type: string
        style: simple
      - explode: true
        in: query
        name: max_channels
        required: false
        schema:
          default: 10
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannelRelatedResponse'
          description: Related channels list retrieved.
        "404":
          description: Channel not found.
      summary: Retrieve related channels by topic
      tags:
      - channels
  /channels/{platform_id}/{channel_id}/topics:
    get:
      description: Returns extracted topics for the specified channel.
      operationId: getChannelTopics
      parameters:
      - explode: false
        in: path
        name: platform_id
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: channel_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannelTopicsResponse'
          description: Topics for the channel retrieved.
        "404":
          description: Channel or topics not found.
      summary: Get extracted topics for a channel
      tags:
      - channels
  /trending/topics:
    get:
      description: "Returns trending topics within a specific time window, including\
        \ associated channels."
      operationId: getTrendingTopics
      parameters:
      - explode: true
        in: query
        name: time_window
        required: true
        schema:
          enum:
          - week
          - month
          - year
          type: string
        style: form
      - explode: true
        in: query
        name: topic_limit
        required: false
        schema:
          default: 10
          type: integer
        style: form
      - explode: true
        in: query
        name: channel_limit
        required: false
        schema:
          default: 5
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrendingTopicsResponse'
          description: Trending topics list retrieved.
        "400":
          description: Invalid parameters.
      summary: Get trending topics
      tags:
      - trending
components:
  schemas:
    ServerRegisterRequest:
      example:
        webhook_url: https://openapi-generator.tech
        name: name
        description: description
        auth_token: auth_token
        platform: matrix
        contact_email: contact_email
      properties:
        platform:
          description: Platform name.
          enum:
          - matrix
          - slack
          - telegram
          - discord
          title: platform
          type: string
        name:
          description: Server/group name.
          title: name
          type: string
        auth_token:
          description: Authentication token.
          title: auth_token
          type: string
        description:
          description: Optional description of the server/group.
          title: description
          type: string
        contact_email:
          description: Optional contact email.
          format: email
          title: contact_email
          type: string
        webhook_url:
          description: Optional URL for webhook updates.
          format: uri
          title: webhook_url
          type: string
      title: ServerRegisterRequest
    ServerRegisterResponse:
      example:
        platform_id: platform_id
        name: name
        platform: platform
        status: registered
      properties:
        platform_id:
          description: Unique ID for the platform server/group.
          title: platform_id
          type: string
        name:
          title: name
          type: string
        platform:
          title: platform
          type: string
        status:
          example: registered
          title: status
          type: string
      title: ServerRegisterResponse
    ChannelMessagesRequest:
      example:
        messages:
        - messages
        - messages
      properties:
        messages:
          description: List of messages for topic extraction.
          items:
            type: string
          type: array
      title: ChannelMessagesRequest
    ChannelMessagesResponse:
      example:
        processed_messages: 0
        success: true
      properties:
        success:
          title: success
          type: boolean
        processed_messages:
          title: processed_messages
          type: integer
      title: ChannelMessagesResponse
    ChannelRelatedResponse:
      example:
        related_channels:
        - platform_id: platform_id
          channel_id: channel_id
          similarity_score: 0.8008282
        - platform_id: platform_id
          channel_id: channel_id
          similarity_score: 0.8008282
      properties:
        related_channels:
          items:
            $ref: '#/components/schemas/RelatedChannel'
          type: array
      title: ChannelRelatedResponse
    RelatedChannel:
      example:
        platform_id: platform_id
        channel_id: channel_id
        similarity_score: 0.8008282
      properties:
        platform_id:
          title: platform_id
          type: string
        channel_id:
          title: channel_id
          type: string
        similarity_score:
          format: float
          title: similarity_score
          type: number
      title: RelatedChannel
    ChannelTopicsResponse:
      example:
        topics:
        - topics
        - topics
        platform_id: platform_id
        channel_id: channel_id
      properties:
        platform_id:
          title: platform_id
          type: string
        channel_id:
          title: channel_id
          type: string
        topics:
          items:
            type: string
          type: array
      title: ChannelTopicsResponse
    TrendingTopicsResponse:
      example:
        time_window: time_window
        topics:
        - channels:
          - platform_id: platform_id
            channel_id: channel_id
            similarity_score: 0.8008282
          - platform_id: platform_id
            channel_id: channel_id
            similarity_score: 0.8008282
          topic: topic
        - channels:
          - platform_id: platform_id
            channel_id: channel_id
            similarity_score: 0.8008282
          - platform_id: platform_id
            channel_id: channel_id
            similarity_score: 0.8008282
          topic: topic
      properties:
        time_window:
          title: time_window
          type: string
        topics:
          items:
            $ref: '#/components/schemas/TrendingTopic'
          type: array
      title: TrendingTopicsResponse
    TrendingTopic:
      example:
        channels:
        - platform_id: platform_id
          channel_id: channel_id
          similarity_score: 0.8008282
        - platform_id: platform_id
          channel_id: channel_id
          similarity_score: 0.8008282
        topic: topic
      properties:
        topic:
          title: topic
          type: string
        channels:
          items:
            $ref: '#/components/schemas/RelatedChannel'
          type: array
      title: TrendingTopic
